name: Integration Tests On Cluster Neo4j 5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CONNECTION: neo4j://neo4j:testtest@localhost7688
    name: "Running on PHP ${{ matrix.php-version }} with a Neo4j ${{ matrix.neo4j-version }} cluster"
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.2"]
        neo4j-version: ["5.1", "5.5"]

    services:
      server1:
        image: neo4j:${{ matrix.neo4j-version }}
        ports:
          - 7688:7688
          - 7475:7475
        env:
          NEO4J_initial_server_mode__constraint=PRIMARY
          NEO4J_dbms_cluster_discovery_endpoints=server1:5000,server2:5000,server3:5000
          NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          NEO4j_server_bolt_advertised_address=localhost:7688
          NEO4j_server_http_advertised_address=localhost:7478
          NEO4J_AUTH=neo4j/mypassword
        options: >-
          --health-cmd "wget -q --method=HEAD http://localhost:7474 || exit 1"
          --health-start-period "60s"
          --health-interval "30s"
          --health-timeout "15s"
          --health-retries "5"
      server2:
        image: neo4j:${{ matrix.neo4j-version }}
        ports:
          - 7689:7689
          - 7476:7476
        env:
          NEO4J_initial_server_mode__constraint=PRIMARY
          NEO4J_dbms_cluster_discovery_endpoints=server1:5000,server2:5000,server3:5000
          NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          NEO4j_server_bolt_advertised_address=localhost:7689
          NEO4j_server_http_advertised_address=server2:7476
          NEO4J_AUTH=neo4j/mypassword
        options: >-
          --health-cmd "wget -q --method=HEAD http://localhost:7474 || exit 1"
          --health-start-period "60s"
          --health-interval "30s"
          --health-timeout "15s"
          --health-retries "5"
      server3:
        image: neo4j:${{ matrix.neo4j-version }}
        ports:
          - 7690:7690
          - 7477:7477
        env:
          NEO4J_initial_server_mode__constraint=PRIMARY
          NEO4J_dbms_cluster_discovery_endpoints=server1:5000,server2:5000,server3:5000
          NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          NEO4j_server_bolt_advertised_address=localhost:7690
          NEO4j_server_http_advertised_address=server3:7477
          NEO4J_AUTH=neo4j/mypassword
        options: >-
          --health-cmd "wget -q --method=HEAD http://localhost:7474 || exit 1"
          --health-start-period "60s"
          --health-interval "30s"
          --health-timeout "15s"
          --health-retries "5"
      read-server4:
        image: neo4j:${{ matrix.neo4j-version }}
        ports:
          - 7691:7691
          - 7478:7478
        env:
          NEO4J_initial_server_mode__constraint=PRIMARY
          NEO4J_dbms_cluster_discovery_endpoints=server1:5000,server2:5000,server3:5000
          NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
          NEO4j_server_bolt_advertised_address=localhost:7691
          NEO4j_server_http_advertised_address=localhost:7478
          NEO4J_AUTH=neo4j/mypassword
        options: >-
          --health-cmd "wget -q --method=HEAD http://localhost:7474 || exit 1"
          --health-start-period "60s"
          --health-interval "30s"
          --health-timeout "15s"
          --health-retries "5"

    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          progress: yes
          php_version: 8.0
          version: 2
      - uses: php-actions/phpunit@v3
        with:
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php-version }}
          memory_limit: 1024M
          version: 9
          testsuite: Integration
          bootstrap: vendor/autoload.php
